package com.gmg;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "DridmePortType", targetNamespace = "http://xmlns.example.com/1399970793097")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DridmePortType {

	/**
	 * 
	 * @param input
	 * @return returns com.gmg.DeleteMedicalContactResponse
	 */
	@WebMethod(operationName = "DeleteMedicalContact", action = "/DridmePortTypeEndpoint/DeleteMedicalContact")
	@WebResult(name = "DeleteMedicalContactResponse", targetNamespace = "http://services.gmg.com/DeleteMedicalContactResponse/1.0", partName = "output")
	public DeleteMedicalContactResponse deleteMedicalContact(
			@WebParam(name = "DeleteMedicalContactRequest", targetNamespace = "http://services.gmg.com/DeleteMedicalContactRequest/1.0", partName = "input") DeleteMedicalContactRequest input);

	/**
	 * 
	 * @param input
	 * @return returns com.gmg.GetMedicalContactsResponse
	 */
	@WebMethod(operationName = "GetMedicalContacts", action = "/DridmePortTypeEndpoint/GetMedicalContacts")
	@WebResult(name = "GetMedicalContactsResponse", targetNamespace = "http://services.gmg.com/GetMedicalContactsResponse/1.0", partName = "output")
	public GetMedicalContactsResponse getMedicalContacts(
			@WebParam(name = "GetMedicalContactsRequest", targetNamespace = "http://services.gmg.com/GetMedicalContactsRequest/1.0", partName = "input") GetMedicalContactsRequest input);

	/**
	 * 
	 * @param input
	 * @return returns com.gmg.InsertMedicalRecordResponse
	 */
	@WebMethod(operationName = "InsertMedicalRecord", action = "/DridmePortTypeEndpoint/InsertMedicalRecord")
	@WebResult(name = "InsertMedicalRecordResponse", targetNamespace = "http://services.gmg.com/InsertMedicalRecordResponse/1.0", partName = "output")
	public InsertMedicalRecordResponse insertMedicalRecord(
			@WebParam(name = "InsertMedicalRecordRequest", targetNamespace = "http://services.gmg.com/InsertMedicalRecordRequest/1.0", partName = "input") InsertMedicalRecordRequest input);

	/**
	 * 
	 * @param input
	 * @return returns com.gmg.UpdateMedicalConditionsResponse
	 */
	@WebMethod(operationName = "UpdateMedicalCondition", action = "/DridmePortTypeEndpoint/UpdateMedicalCondition")
	@WebResult(name = "UpdateMedicalConditionsResponse", targetNamespace = "http://services.gmg.com/UpdateMedicalConditionsResponse/1.0", partName = "output")
	public UpdateMedicalConditionsResponse updateMedicalCondition(
			@WebParam(name = "UpdateMedicalConditionsRequest", targetNamespace = "http://services.gmg.com/UpdateMedicalConditionsRequest/1.0", partName = "input") UpdateMedicalConditionsRequest input);

	/**
	 * 
	 * @param input
	 * @return returns com.gmg.LoginResponse
	 */
	@WebMethod(operationName = "GetLogin", action = "/DridmePortTypeEndpoint/GetLogin")
	@WebResult(name = "LoginResponse", targetNamespace = "http://services.gmg.com/LoginResponse/1.0", partName = "output")
	public LoginResponse getLogin(
			@WebParam(name = "LoginRequest", targetNamespace = "http://services.gmg.com/LoginRequest/1.0", partName = "input") LoginRequest input);

	/**
	 * 
	 * @param input
	 * @return returns com.gmg.UserResponse
	 */
	@WebMethod(operationName = "GetUserProfile", action = "/DridmePortTypeEndpoint/GetUserProfile")
	@WebResult(name = "UserResponse", targetNamespace = "http://services.gmg.com/UserResponse/1.0", partName = "output")
	public UserResponse getUserProfile(
			@WebParam(name = "GetUserRequest", targetNamespace = "http://services.gmg.com/GetUserRequest/1.0", partName = "input") GetUserRequest input);

	/**
	 * 
	 * @param input
	 * @return returns com.gmg.DeleteMedicalConditionResponse
	 */
	@WebMethod(operationName = "DeleteMedicalCondition", action = "/DridmePortTypeEndpoint/DeleteMedicalCondition")
	@WebResult(name = "DeleteMedicalConditionResponse", targetNamespace = "http://services.gmg.com/DeleteMedicalConditionResponse/1.0", partName = "output")
	public DeleteMedicalConditionResponse deleteMedicalCondition(
			@WebParam(name = "DeleteMedicalConditionRequest", targetNamespace = "http://services.gmg.com/DeleteMedicalConditionRequest/1.0", partName = "input") DeleteMedicalConditionRequest input);

	/**
	 * 
	 * @param input
	 * @return returns com.gmg.InsertMedicalContactResponse
	 */
	@WebMethod(operationName = "InsertMedicalContact", action = "/DridmePortTypeEndpoint/InsertMedicalContact")
	@WebResult(name = "InsertMedicalContactResponse", targetNamespace = "http://services.gmg.com/InsertMedicalContactResponse/1.0", partName = "output")
	public InsertMedicalContactResponse insertMedicalContact(
			@WebParam(name = "InsertMedicalContactRequest", targetNamespace = "http://services.gmg.com/InsertMedicalContactRequest/1.0", partName = "input") InsertMedicalContactRequest input);

	/**
	 * 
	 * @param input
	 * @return returns com.gmg.UpdateUserResponse
	 */
	@WebMethod(operationName = "UpdateUserProfile", action = "/DridmePortTypeEndpoint/UpdateUserProfile")
	@WebResult(name = "UpdateUserResponse", targetNamespace = "http://services.gmg.com/UpdateUserResponse/1.0", partName = "output")
	public UpdateUserResponse updateUserProfile(
			@WebParam(name = "UserRequest", targetNamespace = "http://services.gmg.com/UserRequest/1.0", partName = "input") UserRequest input);

	/**
	 * 
	 * @param input
	 * @return returns com.gmg.GetMedicalRecordsResponse
	 */
	@WebMethod(operationName = "GetMedicalRecords", action = "/DridmePortTypeEndpoint/GetMedicalRecords")
	@WebResult(name = "GetMedicalRecordsResponse", targetNamespace = "http://services.gmg.com/GetMedicalRecordsResponse/1.0", partName = "output")
	public GetMedicalRecordsResponse getMedicalRecords(
			@WebParam(name = "GetMedicalRecordsRequest", targetNamespace = "http://services.gmg.com/GetMedicalRecordsRequest/1.0", partName = "input") GetMedicalRecordsRequest input);

	/**
	 * 
	 * @param input
	 * @return returns com.gmg.GetMedicalConditionsResponse
	 */
	@WebMethod(operationName = "GetMedicalConditions", action = "/DridmePortTypeEndpoint/GetMedicalConditions")
	@WebResult(name = "GetMedicalConditionsResponse", targetNamespace = "http://services.gmg.com/GetMedicalConditionsResponse/1.0", partName = "output")
	public GetMedicalConditionsResponse getMedicalConditions(
			@WebParam(name = "GetMedicalConditionsRequest", targetNamespace = "http://services.gmg.com/GetMedicalConditionsRequest/1.0", partName = "input") GetMedicalConditionsRequest input);

	/**
	 * 
	 * @param input
	 * @return returns com.gmg.InsertMedicalConditionResponse
	 */
	@WebMethod(operationName = "InsertMedicalCondition", action = "/DridmePortTypeEndpoint/InsertMedicalCondition")
	@WebResult(name = "InsertMedicalConditionResponse", targetNamespace = "http://services.gmg.com/InsertMedicalConditionResponse/1.0", partName = "output")
	public InsertMedicalConditionResponse insertMedicalCondition(
			@WebParam(name = "InsertMedicalConditionRequest", targetNamespace = "http://services.gmg.com/InsertMedicalConditionRequest/1.0", partName = "input") InsertMedicalConditionRequest input);

	/**
	 * 
	 * @param input
	 * @return returns com.gmg.UpdateMedicalContactResponse
	 */
	@WebMethod(operationName = "UpdateMedicalContact", action = "/DridmePortTypeEndpoint/UpdateMedicalContact")
	@WebResult(name = "UpdateMedicalContactResponse", targetNamespace = "http://services.gmg.com/UpdateMedicalContactResponse/1.0", partName = "output")
	public UpdateMedicalContactResponse updateMedicalContact(
			@WebParam(name = "UpdateMedicalContactRequest", targetNamespace = "http://services.gmg.com/UpdateMedicalContactRequest/1.0", partName = "input") UpdateMedicalContactRequest input);

	/**
	 * 
	 * @param input
	 * @return returns com.gmg.ChangePasswordResponse
	 */
	@WebMethod(operationName = "ChangePassword", action = "/DridmePortTypeEndpoint/ChangePassword")
	@WebResult(name = "ChangePasswordResponse", targetNamespace = "http://piglet.healthcodex.com/ChangePasswordResponse/1.0", partName = "output")
	public ChangePasswordResponse changePassword(
			@WebParam(name = "ChangePasswordRequest", targetNamespace = "http://piglet.healthcodex.com/ChangePasswordRequest/1.0", partName = "input") ChangePasswordRequest input);

	/**
	 * 
	 * @param input
	 * @return returns com.gmg.ResetPasswordResponse
	 */
	@WebMethod(operationName = "ResetPassword", action = "/DridmePortTypeEndpoint/ResetPassword")
	@WebResult(name = "ResetPasswordResponse", targetNamespace = "http://piglet.healthcodex.com/ResetPasswordResponse/1.0", partName = "output")
	public ResetPasswordResponse resetPassword(
			@WebParam(name = "ResetPasswordRequest", targetNamespace = "http://piglet.healthcodex.com/ResetPasswordRequest/1.0", partName = "input") ResetPasswordRequest input);

}
